export const strapiTypes = {
    START_ADD_NEW_USER: 'START ADD NEW USER',
    NEW_USER_ADDED_SUCCESS: 'NEW USER ADDED SUCCESS',
    LOGIN_USER_START: 'LOGIN USER START',
    LOGIN_USER_SUCESS: 'LOGIN USER SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN USER ERROR',
    ERROR_ADDING_USER: 'ERROR ADDING USER',
    ADD_TOKEN: 'ADD TOKEN'
}